c_temp = int(input("insert celcius temperature : "))
f_solve = str(9/5 * (c_temp +32 ))
print("The temperature in Fahrenheit unit is:",f_solve,"F")
print("The temperature in Fahrenheit unit is: " + f_solve + " F ")
print("The temperature in Fahrenheit unit is: {} F ".format(f_solve))
print(f"The temperature in Fahrenheit unit is: {f_solve} F ")